version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ubuntu/app

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 755

hooks:
  ApplicationStart:
    - location: deploy.sh
      timeout: 60
      runas: root