package com.sparta.doblock.events.entity;

public enum BadgeType {

    COMPLETED_TODO_TEN,
    COMPLETED_TODO_FIFTY,
    COMPLETED_TODO_HUNDRED,

    CREATED_FEED_TEN,
    CREATED_FEED_FIFTY,
    CREATED_FEED_HUNDRED,

    CREATED_REACTION_TEN,
    CREATED_REACTION_FIFTY,
    CREATED_REACTION_HUNDRED,

    CREATED_COMMENT_TEN,
    CREATED_COMMENT_FIFTY,
    CREATED_COMMENT_HUNDRED,

    FOLLOW_TO_MEMBER_TEN,
    FOLLOW_TO_MEMBER_FIFTY,
    FOLLOW_TO_MEMBER_HUNDRED
}
