package com.sparta.doblock.events.entity;

public enum BadgeType {

    COMPLETED_TODO_TEN,
    COMPLETED_TODO_FIFTY,
    COMPLETED_TODO_HUNDRED,

    CREATED_FEED_TEN,
    CREATED_FEED_FIFTY,
    CREATED_FEED_HUNDRED,

    SOCIAL_ACTIVE_TEN,
    SOCIAL_ACTIVE_FIFTY,
    SOCIAL_ACTIVE_HUNDRED,

    FOLLOW_TO_MEMBER_TEN,
    FOLLOW_TO_MEMBER_FIFTY,
    FOLLOW_TO_MEMBER_HUNDRED;
}
